### ISSUE TITLE
Preparing 5.x for release

### ISSUE THREAD

**Issue by DonutEspresso** [restify/node-restify#1082]
I'd like to get 5.x out before end of the month (aggressive!). There are a few remaining issues I'd like resolve, assigning to core team members but also happy to accept help if any is offered from the community! 

@yunong
- [x] [RequestCaptureStream does not write triggering record](https://github.com/restify/node-restify/issues/958) . The PR exists but needs review. 
- [x] [Losing params mapping on chained handler](https://github.com/restify/node-restify/issues/1050). No PR, needs some feedback from @yunong and I can create a PR. 

@donutespresso
- [x] [Custom handler => 404 will not send response](https://github.com/restify/node-restify/issues/999). Needs feedback from @yunong @micahr
- [x] [Formatters](https://github.com/restify/node-restify/pull/1084) PR exists but needs some cleanup.
- [x] [Add Response.sendRaw for sending without formatting](https://github.com/restify/node-restify/pull/1025)
- [x] [5.x migration guide](https://github.com/restify/node-restify/issues/1096)
- [x] [Allow the request id header to be configured](https://github.com/restify/node-restify/issues/1086)
- [x] [res.send() needs to be async to accommodate async formatters](https://github.com/restify/node-restify/issues/845)
- [x] [set res.statusCode to 0 for requests closed by the client](https://github.com/restify/node-restify/issues/1119)

looking for help!
- [x] [Support strict routing](https://github.com/restify/node-restify/issues/692) - looking for contributors on this one!

**Comment by lukealbao** [comment]
I'd like to help with the strict routing if you're still looking for someone.

**Comment by DonutEspresso** [comment]
@lukealbao, thank you for the offer! It's all yours. :)

**Comment by KostyaTretyak** [comment]
I'm just wondering why in branch 5.x we have package.json, where write version 4.0.3?

**Comment by DonutEspresso** [comment]
@KostyaTretyak you can use the git URL if you want to consume 5.x directly. We'd like to get a 5.x-RC1 out soon, but we haven't had time to wrap up a few loose ends.

**Comment by artmunro** [comment]
Any update on 5.0 release?

**Comment by chb0github** [comment]
is Restify done for? I actually contributed code for the "upcoming" 5.0 release like, 2 years ago!

**Comment by DonutEspresso** [comment]
Sorry, we have been internally revving betas and doing further testing - just released a beta8 today! It is still being actively maintained, and there is a lot of upcoming work we want to do. 

We will have an update for the community in the following weeks regarding our roadmap.

**Comment by retrohacker** [comment]
It looks like all of the issues here have been resolved. There are still a few outstanding issues on the 5.x milestone. Can we close this issue in favor of the milestone?

**Comment by retrohacker** [comment]
Oops, wrong button :blush:

**Comment by DonutEspresso** [comment]
Sounds good to me. Can you link the milestone issue (if one exists already) and close this one?

**Comment by retrohacker** [comment]
https://github.com/restify/node-restify/milestone/8
